name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    name: >-
      ruby ${{ matrix.ruby }}, resque ${{ matrix.resque }}, redis ${{ matrix.redis }}, ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04 ]
        ruby: [ "2.4", "2.5", "2.6", "2.7", "3.0", "3.1", "3.2", "3.3" ]
        resque: [ "1.22", "1.23", "1.24", "1.25", "1.26", "1.27", "2.0", "2.1", "2.2", "2.3", "2.4", "2.5", "2.6" ]

        include:
          - { resque: "1.22", redis: "2.0" }
          - { resque: "1.23", redis: "3.0" }
          - { resque: "1.24", redis: "3.0" }
          - { resque: "1.25", redis: "3.0" }
          - { resque: "1.26", redis: "3.2" }
          - { resque: "1.27", redis: "3.3" }
          - { resque: "2.0",  redis: "4.0" }
          - { resque: "2.1",  redis: "4.4" }
          - { resque: "2.2",  redis: "4.6" }
          - { resque: "2.3",  redis: "4.7" }
          - { resque: "2.4",  redis: "4.8" }
          - { resque: "2.5",  redis: "5.0" }
          - { resque: "2.6",  redis: "5.2" }

          - os: ubuntu-20.04
            ruby: "3.3"
            resque: "2.6"
            redis: "5.2"


    services:
      redis:
        image: redis

    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/resque_${{ matrix.resque }}_redis_${{ matrix.redis }}.gemfile

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: sudo apt-get install redis-server
    - name: Run specs
      run: bundle exec rake
